### ISSUE TITLE
Removing a route does remove it from the list of recognised routes, and therefore doesn't invoke the fallback

### ISSUE THREAD

**Issue by jfstephe** [aurelia/route-recognizer#28]
**I'm submitting a bug report**

* **Library Version:**
1.1.0

**Current behavior:**
As suggested [here](https://github.com/aurelia/router/issues/129) removing a route can be done by removing the NavModel from the list of routes the router current has. That works fine but if you add and then remove a route for '#/test/', for example, then navigating to that still 'works' as far as the router is concerned. It never hits the fallback url.

**Expected/desired behavior:**
* **What is the expected behavior?**
Add a removeRoute function on the router which removes the route from the list and updates the state information in the route-recognizer, so that navigating to a removed route hits the fallback route as appropriate.

* **What is the motivation / use case for changing the behavior?**
It's a bug (if you treat [this](https://github.com/aurelia/router/issues/129) as official advice or missing feature. Either way would be good to have a fix, and/or a short term workaround please :-).

**Comment by EisenbergEffect** [comment]
Closing this for now since it's been a while since the initial submission and we haven't had a community contribution or additional requests. Additionally, some alternative approaches for the use cases have been provided in other threads. Finally, we're making some big improvements, in general, to routing in vNext, which is our biggest area of routing improvement focus now and going forward.
